# Generated by Django 5.2.16 on 2026-07-17 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="accounts.child",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="catalog.classsession",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "child"), name="uniq_attendance"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested (awaiting confirmation)"),
                            ("ENROLLED", "Enrolled"),
                            ("WAITLISTED", "On waiting list"),
                            ("OFFERED", "Seat offered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("waitlisted_at", models.DateTimeField(blank=True, null=True)),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PARENT", "Cancelled by parent"),
                            ("ADMIN", "Cancelled by school"),
                            ("REQUEST_REJECTED", "Request not approved"),
                            ("CLASS_CANCELLED", "Class cancelled"),
                            ("OFFER_EXPIRED", "Offer expired"),
                            ("OFFER_DECLINED", "Offer declined"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("promoted_from_waitlist", models.BooleanField(default=False)),
                (
                    "activity_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="catalog.activityclass",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.child",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who last approved/rejected/offered.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "offer_expires_at"],
                        name="enrollments_status_910067_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "CANCELLED"), _negated=True),
                        fields=("child", "activity_class"),
                        name="uniq_active_enrollment",
                    )
                ],
            },
        ),
    ]
