# Generated by Django 5.2.17 on 2026-09-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_enrollment_terms_accepted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="cancel_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the family asked to cancel a confirmed place after the withdrawal window; cleared when an admin confirms or keeps the place.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="cancel_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARENT", "Withdrawn by parent"),
                    ("PARENT_REQUEST", "Cancelled at the family's request"),
                    ("ADMIN", "Cancelled by school"),
                    ("REQUEST_REJECTED", "Request not approved"),
                    ("CLASS_CANCELLED", "Class cancelled"),
                    ("OFFER_EXPIRED", "Offer expired"),
                    ("OFFER_DECLINED", "Offer declined"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
