# Generated by Django 5.2.17 on 2026-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_enrolment_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARENT", "Withdrawn by parent"),
                    ("PARENT_REQUEST", "Cancelled at the family's request"),
                    ("ADMIN", "Cancelled by school"),
                    ("REQUEST_REJECTED", "Request not approved"),
                    ("CLASS_CANCELLED", "Class cancelled"),
                    ("OFFER_EXPIRED", "Offer expired"),
                    ("OFFER_DECLINED", "Offer declined"),
                    ("TRANSFERRED", "Moved to another class"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
