# Generated by Django 5.2.17 on 2026-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="may_leave_alone",
            field=models.BooleanField(
                default=False,
                help_text="Tick if this child is authorised to leave an activity unaccompanied. Providers only act on what is recorded here, never on verbal instructions.",
                verbose_name="may go home on their own",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="school_class",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Primary",
                        [
                            ("P1E", "P1E · English section"),
                            ("P1S", "P1S · Slovenian section"),
                            ("P2E", "P2E · English section"),
                            ("P2S", "P2S · Slovenian section"),
                            ("P3E", "P3E · English section"),
                            ("P3S", "P3S · Slovenian section"),
                            ("P4E", "P4E · English section"),
                            ("P4S", "P4S · Slovenian section"),
                            ("P5E", "P5E · English section"),
                            ("P5S", "P5S · Slovenian section"),
                        ],
                    ),
                    (
                        "Secondary",
                        [
                            ("S1E", "S1E · English section"),
                            ("S1S", "S1S · Slovenian section"),
                            ("S2E", "S2E · English section"),
                            ("S2S", "S2S · Slovenian section"),
                            ("S3E", "S3E · English section"),
                            ("S3S", "S3S · Slovenian section"),
                            ("S4E", "S4E · English section"),
                            ("S4S", "S4S · Slovenian section"),
                            ("S5E", "S5E · English section"),
                            ("S5S", "S5S · Slovenian section"),
                            ("S6E", "S6E · English section"),
                            ("S6S", "S6S · Slovenian section"),
                            ("S7E", "S7E · English section"),
                            ("S7S", "S7S · Slovenian section"),
                        ],
                    ),
                ],
                help_text="The child's class this school year, e.g. P3E or S2S.",
                max_length=4,
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="sender_name",
            field=models.CharField(
                default="European School PTA",
                help_text="Who signs the emails parents receive, e.g. “European School PTA”.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="terms_markdown",
            field=models.TextField(
                blank=True,
                default="# Extra-Curricular Activities — Terms & Conditions\n\nThe extra-curricular programme is organised by the PTA on a fully voluntary basis. Parent volunteers find providers, negotiate rates and conditions, and run enrolment. Nobody is paid for this.\n\nPlease read these terms before enrolling — they exist to keep classes viable and the programme sustainable.\n\n## Our role — and who you're actually contracting with\n\nThe PTA negotiates with providers on behalf of parents and coordinates enrolment. We take provider selection seriously: we've put considerable effort into vetting everyone on this year's programme. All providers work or have worked with other schools, and we ask for and check the certifications and qualifications appropriate to their activity.\n\nThat said, once your child has a place, the agreement is directly between you and the provider. The PTA is not a party to it, does not employ providers, and cannot take final responsibility for the delivery, quality or safety of an activity. We've done our best to choose well, but we're parent volunteers, not a licensing authority.\n\nConcerns about a class are best raised with the provider first. If something isn't resolved, tell us — we'll take it up with them and in the next round of negotiations.\n\n## Enrolment\n\nAll registrations must be made through the web form on the PTA website. We can't accept enrolments by email, message, in person, or via the provider — if it isn't on the form, the place doesn't exist.\n\n## Payments\n\nFees are paid directly to the provider, monthly or per semester, on the terms agreed with them. The PTA does not collect or handle any money.\n\n## Cancellations and withdrawals\n\nWithdrawals are processed through the PTA website, not directly with the provider. This keeps waiting lists and class numbers accurate for everyone.\n\n## Absences and refunds\n\nNo refunds are given for absences, except for a justified absence of more than three weeks. Providers commit staff and space for the full semester, and every class needs a critical mass of children to run at all.\n\nYou don't need to notify providers of individual absences — the teacher tells the provider at pick-up. The exception is individual music lessons, where the provider should be informed directly.\n\n## Pick-up (primary cycle)\n\nChildren in primary must be collected promptly at the end of the activity. Providers finish when the session finishes; late collection means someone is supervising your child unpaid, often while another class is waiting to start.\n\nRepeated late collection may result in a child losing their place in the activity. If your child is authorised to leave on their own, this must be stated on the registration form — providers cannot act on verbal instructions.\n\n## Feedback\n\nOnce per semester we circulate a short questionnaire. Please complete it — it's the only systematic evidence we have when renegotiating with providers, and it directly shapes what we offer next year.\n",
                help_text="Markdown. Shown at /terms/ and linked from the navigation; parents must confirm they have read it before registering. Leave empty to hide it.",
                verbose_name="terms and conditions",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="surname"),
        ),
    ]
