# Generated by Django 5.2.17 on 2026-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_withdrawal_window_editable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "School admin"),
                    ("READONLY", "School admin (read-only)"),
                    ("PROVIDER", "Course provider"),
                    ("PARENT", "Parent"),
                ],
                default="PARENT",
                max_length=10,
            ),
        ),
    ]
