# Generated by Django 5.2.17 on 2026-09-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityclass",
            name="runs_during_holidays",
            field=models.BooleanField(
                default=False,
                help_text="School holidays are skipped when sessions are generated. Tick this for holiday camps and clubs that meet while school is out.",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="holiday_override",
            field=models.BooleanField(
                default=False,
                help_text="Keep this session even though it falls in a school holiday. Set it on the one-off dates a class does meet over the break.",
                verbose_name="runs despite holiday",
            ),
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For example 2026/27.", max_length=100, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="school_year_dates_valid",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="term",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Terms in a school year inherit its holidays.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms",
                to="catalog.schoolyear",
            ),
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For example Christmas break.", max_length=120
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        help_text="Inclusive. For a single day, repeat the start date."
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="catalog.schoolyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "school holiday",
                "verbose_name_plural": "school holidays",
                "ordering": ["start_date", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="holiday_dates_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("school_year", "name", "start_date"),
                        name="uniq_holiday_per_year",
                    ),
                ],
            },
        ),
    ]
