# Generated by Django 5.2.17 on 2026-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_recommended_age_range"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activityclass",
            name="capacity_positive",
        ),
        migrations.AlterField(
            model_name="activityclass",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Places offered. Set 0 for a waiting-list-only class: parents can still register, but nobody is given a place until the capacity is raised.",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 0)), name="capacity_not_negative"
            ),
        ),
    ]
