# Generated by Django 5.2.17 on 2026-09-03 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_waiting_list_only_classes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityclass",
            name="administrators",
            field=models.ManyToManyField(
                blank=True,
                help_text="School admins responsible for this class: they alone see its requests and receive its alerts. Leave empty to leave it with the general administrators (admins with no classes of their own).",
                limit_choices_to={"is_active": True, "role": "ADMIN"},
                related_name="managed_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
