# Generated by Django 5.2.17 on 2026-09-03 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_class_administrators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityclass",
            name="administrators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Admins responsible for this class: they see and act on its requests and receive its alerts. Super admins (superusers) always see every class; a class with nobody assigned alerts them.",
                limit_choices_to={"is_active": True, "role": "ADMIN"},
                related_name="managed_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
