# Generated by Django 5.2.17 on 2026-09-13 06:50

import apps.media.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_administrators_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="The provider's own accounts (provider role): they see every class of this provider, message its families, and manage its instructors and their accounts from the provider dashboard.",
                related_name="provider_orgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A few lines parents will read on the class page: what you teach, your background, what a session with you is like.",
                        max_length=1500,
                        verbose_name="about you",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. Shown next to your name on the class page.",
                        upload_to="instructors/",
                    ),
                ),
                (
                    "conduct_certificate",
                    models.FileField(
                        blank=True,
                        help_text="PDF or a photo of the certificate. Only you, your provider and the school office can open it.",
                        storage=apps.media.storage.private_storage,
                        upload_to="private/conduct-certificates/",
                        verbose_name="certificate of police conduct",
                    ),
                ),
                (
                    "conduct_certificate_issued_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="certificate issued on"
                    ),
                ),
                (
                    "conduct_certificate_uploaded_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "conduct_certificate_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by the school office once it has looked at the certificate. Parents then see that it has been checked. Cleared automatically when a new file is uploaded.",
                        null=True,
                        verbose_name="certificate checked on",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conduct_certificate_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="catalog.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name", "user__email"],
            },
        ),
        migrations.AddField(
            model_name="activityclass",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who teaches this class. Only the provider's own instructors can be chosen; they see the class, its register and its attendance on their dashboard, and their profiles appear on the class page.",
                related_name="classes",
                to="catalog.instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="instructor",
            constraint=models.UniqueConstraint(
                fields=("provider", "user"), name="uniq_instructor_per_provider"
            ),
        ),
    ]
