# Generated by Django 5.2.16 on 2026-07-17 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_REQUESTED", "Enrollment requested (receipt)"),
                            ("REGISTRATION_CONFIRMED", "Registration confirmed"),
                            ("REQUEST_REJECTED", "Request not approved"),
                            ("WAITLISTED", "Added to waiting list"),
                            ("WAITLIST_OFFER", "Seat offered from waiting list"),
                            ("OFFER_EXPIRED", "Waiting-list offer expired"),
                            ("SUBSCRIPTION_CANCELLED", "Enrollment cancelled"),
                            ("CLASS_CANCELLED", "Class cancelled"),
                            ("GUARDIAN_INVITE", "Co-parent invitation"),
                            ("BROADCAST", "Announcement"),
                            ("ADMIN_NEW_REQUEST", "Admin: new enrollment request"),
                            ("ADMIN_SEAT_FREED", "Admin: seat freed"),
                            ("ADMIN_OFFER_LAPSED", "Admin: offer declined/expired"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("email_subject", models.CharField(max_length=300)),
                ("email_body", models.TextField()),
                ("wa_template_name", models.CharField(blank=True, max_length=100)),
                ("wa_language", models.CharField(default="en", max_length=10)),
                (
                    "wa_param_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Context keys for the template placeholders, e.g. ["child_name", "class_title"]',
                    ),
                ),
            ],
            options={
                "ordering": ["event"],
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ALL_CLASSES", "All published classes"),
                            ("SELECTED_CLASSES", "Selected classes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="broadcasts",
                        to="catalog.activityclass",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("WHATSAPP", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_REQUESTED", "Enrollment requested (receipt)"),
                            ("REGISTRATION_CONFIRMED", "Registration confirmed"),
                            ("REQUEST_REJECTED", "Request not approved"),
                            ("WAITLISTED", "Added to waiting list"),
                            ("WAITLIST_OFFER", "Seat offered from waiting list"),
                            ("OFFER_EXPIRED", "Waiting-list offer expired"),
                            ("SUBSCRIPTION_CANCELLED", "Enrollment cancelled"),
                            ("CLASS_CANCELLED", "Class cancelled"),
                            ("GUARDIAN_INVITE", "Co-parent invitation"),
                            ("BROADCAST", "Announcement"),
                            ("ADMIN_NEW_REQUEST", "Admin: new enrollment request"),
                            ("ADMIN_SEAT_FREED", "Admin: seat freed"),
                            ("ADMIN_OFFER_LAPSED", "Admin: offer declined/expired"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rendered_subject", models.CharField(blank=True, max_length=300)),
                ("rendered_body", models.TextField(blank=True)),
                ("wa_template_name", models.CharField(blank=True, max_length=100)),
                ("wa_language", models.CharField(blank=True, max_length=10)),
                ("wa_params", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("skip_reason", models.CharField(blank=True, max_length=100)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.broadcast",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="notificatio_status_444bb6_idx",
                    )
                ],
            },
        ),
    ]
