# Generated by Django 5.2.17 on 2026-09-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_contact_form_messages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
            },
        ),
    ]
